### ISSUE TITLE
[fea] motif discovery - analysis block

### ISSUE THREAD

**Issue by suzannejin** [mathysgrapotte/stimulus#103]
All the functionalities that are needed for the domain specific analysis related to motif discovery.

How do the PWM look like?

- [ ] Use HOMER to compute PWM
- [ ] For classification task: positive vs negative (background)
- [ ] For regression task: top 25% vs bottom 25% (or a flag x%)
- [ ] For convolution filters

How similar are the data in terms of PWMs?

- [ ] Compute TOMTOM score
- [ ] **Between input vs model predictions**
- [ ] Between original input data and transformed data

**Comment by mathysgrapotte** [comment]
see [stimulus-py](https://github.com/mathysgrapotte/stimulus-py)
