### ISSUE TITLE
[feat] take as input Yaml for transform and split information

### ISSUE THREAD

**Issue by alessiovignoli** [mathysgrapotte/stimulus#117]
Here is a list of things that should change while that transition happen:

- [ ] [bug] consecutive calls of tranformers on same column only work inside "custom" flag. The possibility to deploy more than one transformation on the same column is curently supported at python level but not at nextflow level.
- [ ] [feat] set a yaml architecture that fits all possible combinations of transformers. Considering that consecutive calls of methods on the same column are now allowed.
- [ ] [feat] either using nextflow schema or through custom script check that all the necesasary fields are preent and that they are of the correct type and relationships among each other.
- [ ] [feat] write documentation (brief) on how to use and what to specify for the user.

**Comment by mathysgrapotte** [comment]
see [stimulus-py](https://github.com/mathysgrapotte/stimulus-py)
