### ISSUE TITLE
[analysis] provide a report of auc vs data modification

### ISSUE THREAD

**Issue by suzannejin** [mathysgrapotte/stimulus#136]
1. we first fix the data. So for example fix the data to not modified bind set.
2. Then compute the AUC of models trained on different data modifications
3. Plot test data modification as X, AUC as Y, and color the models based on which data modification is used to train the model.
4. Or plot a heatmap with X as blind set data modifications and Y as model modifications, and AUC values. But always with fixed to one kind of data modification per heatmap to have a meaningful analysis

**Comment by mathysgrapotte** [comment]
cf [stimulus-py](https://github.com/mathysgrapotte/stimulus-py)
