### ISSUE TITLE
[fix] ray tune runs forever sometimes 

### ISSUE THREAD

**Issue by suzannejin** [mathysgrapotte/stimulus#143]
sometimes, ray tune stays forever in running mode for some samples, 
and then these samples don't progress. And stay in the same iteration forever.

**Comment by alessiovignoli** [comment]
this does not happen on github actions, i think is a cluster issue.

**Comment by mathysgrapotte** [comment]
Should be fix by using proper ressources declaration, see #154 @alessiovignoli

**Comment by mathysgrapotte** [comment]
Could also be linked to #155
