### ISSUE TITLE
[feat] add a check on split parameters values. 

### ISSUE THREAD

**Issue by alessiovignoli** [mathysgrapotte/stimulus#151]
The split functions can work with a set of values like this -> [1.0, 0.0, 0.0]. basically the can handle a zero on a given set.
Problem is that an empty set fucks up the pipeline in terrible ways.

Easy solution: when the input experiment config is passed the values are read and if there is a 0 throw an error to the user.

**Comment by mathysgrapotte** [comment]
cf [stimulus-py](https://github.com/mathysgrapotte/stimulus-py)
