### ISSUE TITLE
Use a config in json format to parse de parameters in nextflow through the python code

### ISSUE THREAD

**Issue by mathysgrapotte** [mathysgrapotte/stimulus#16]

**Comment by mathysgrapotte** [comment]
Should we by default pass the csv file randomly splitted ? if yes, how ?

**Comment by mathysgrapotte** [comment]
@alessiovignoli can we consider this issue solved ? Otherwise can we have a description of what has been done so far on this ?

**Comment by alessiovignoli** [comment]
The issue can be solved, what has been done is setting the structure of the Json. (not checking it thorougly) for now. Then all the function needed to interpret the noise and split aparameters. The only function missing in that sense is the interpretation of the noise parameters in a all vs all manner.
