### ISSUE TITLE
[feat] parallelize predict wrapper

### ISSUE THREAD

**Issue by suzannejin** [mathysgrapotte/stimulus#178]

**Comment by mathysgrapotte** [comment]
@suzannejin what do you mean by this ?

**Comment by suzannejin** [comment]
@mathysgrapotte the PredictWrapper code is not parallelized. Meaning only one core is used to predict on new data using the trained model.
Sometimes when data is big (like for example in ibis it takes longer predicting than training), we might need this.

**Comment by mathysgrapotte** [comment]
should be adressed in [stimulus-py](https://github.com/mathysgrapotte/stimulus-py)
