### ISSUE TITLE
add .vscode/settings.json to allow testing and debugging of the unit tests inside vscode

### ISSUE THREAD

**Issue by suzannejin** [mathysgrapotte/stimulus#20]

**Comment by mathysgrapotte** [comment]
.vscode/settings.json is currently included in .gitignore and I believe should be unique to each user, thoughts ?

**Comment by suzannejin** [comment]
in theory it should be depending on the package structure no?

**Comment by mathysgrapotte** [comment]
I mean that not everyone uses vscode for testing, additionaly, you may want to modify the testing scheme depending on your usecase in vscode locally (for instance using unittest or pytest which yield different results), also, those files might differ depending on vscode version!

**Comment by suzannejin** [comment]
so you suggest we don't put it in github, and each of us use it independently?

**Comment by mathysgrapotte** [comment]
Yes !
