### ISSUE TITLE
Write protein data type

### ISSUE THREAD

**Issue by suzannejin** [mathysgrapotte/stimulus#21]

**Comment by mathysgrapotte** [comment]
see #26 for how to write this in the new experiment class format.

**Comment by mathysgrapotte** [comment]
In this case, I could see that UniformTextMasker noiser would need a 'mask' attribute that would be passed to __init__ (would be 'N' for dna and 'X' for protein)

**Comment by suzannejin** [comment]
> In this case, I could see that UniformTextMasker noiser would need a 'mask' attribute that would be passed to **init** (would be 'N' for dna and 'X' for protein)

ehhh i just put it there too
