### ISSUE TITLE
Checking correctness of Json for noise and split parameters.

### ISSUE THREAD

**Issue by alessiovignoli** [mathysgrapotte/stimulus#50]
As described above the Json schema can be implemented using this module [Here](https://json-schema.org/learn/getting-started-step-by-step#create).

The schema is just a fancy word to describe all the operations that have to be made on the Json to make sure it has the right structure and datatypes.

**Comment by alessiovignoli** [comment]
On this topic check what happens (allow it or not) when the user specifies "noise" : None .

**Comment by mathysgrapotte** [comment]
should be done in [stimulus-py](https://github.com/mathysgrapotte/stimulus-py)
