### ISSUE TITLE
Add tests that considers the reproducibility & random seeds

### ISSUE THREAD

**Issue by suzannejin** [mathysgrapotte/stimulus#56]

**Comment by luisas** [comment]
Which kind of tests exactly?

For example in the training we have this

https://github.com/mathysgrapotte/stimulus/blob/46a77cf280f4bb126bb0ff931d4d11d10d427dac/bin/tests/test_raytune_learner.py#L13

and the exact output of the models are checked. 

Is this what you meant? If so, maybe we can close it :)
