### ISSUE TITLE
stimulus to chose the arquitecture and finish the training of the best one(s) chosen by user

### ISSUE THREAD

**Issue by suzannejin** [mathysgrapotte/stimulus#69]
stimulus goal -> to provide a report on the most robust arquitecture.
This behaviour should be fully traceable through the different branches of configs, and tunings.
So for each arquitechture, it will be paired with the corresponding config, and report, and data, etc.

Then, the user choses which arquitecture they want to use based on the reports.
Once they have chosen, stimulus show be able to focus on the chosen branches,
and finish the final trainings.

**Comment by mathysgrapotte** [comment]
has been debated that stimulus would perform the final training, only provide the architecture to train on for now
