### ISSUE TITLE
[feat] data augmentation

### ISSUE THREAD

**Issue by mathysgrapotte** [mathysgrapotte/stimulus#75]
We should be able to augment data (as opposed to noise data) as a way to allow for constructing better datasets (should improve training vs decrease training power). 

Data augmentation should only happen on the train set
Data augmentation should happen after noise and after data has been joined (in the event of column splitting)

- [x] add an add_augmentation method to the csv class in python that adds data (duplicates).
- [x] add augmentation methods in augmentation/augmentation_generators.py
- [x] check if the experiment class can handle data augmentation
- [x] write tests for both experiment and augmentation classes
- [x] allow json schemer to handle user input augmentation method

**Comment by luisas** [comment]
Python part is completed in #96

**Comment by alessiovignoli** [comment]
nextflow part is completed in #118
