### ISSUE TITLE
[feat] use safetensors to save and load model weights

### ISSUE THREAD

**Issue by suzannejin** [mathysgrapotte/stimulus#91]
https://huggingface.co/docs/safetensors/index

**Comment by mathysgrapotte** [comment]
![image](https://github.com/user-attachments/assets/641a7ff6-39a2-4e2a-b07d-c363ccf90dc7)
save_model and load_model seem to be doing what we want, safetensors allows for saving part of a model as well.

**Comment by mathysgrapotte** [comment]
Every process saving or loading tensors

- torch_tune with initial weights (in the code)

**Comment by mathysgrapotte** [comment]
Currently, loading from pretrained needs to happen at the user-provided code level, this can be improved by safetensors (or default pytorch load_state_dict) by setting the strict argument to false 
```py
model = Model()
safetensors.torch.save_model(model, "model.safetensors")
biggermodel = BiggerModel()
safetensors.torch.load_model(biggermodel, "model.safetensors", strict = False) 
```

Here, biggermodel has an extra layer vs model, it will load the common part correctly

**Comment by mathysgrapotte** [comment]
done in #182
